version: '2'
services:
  formica:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws
      - /app/formica_cli.egg-info
      - /app/build
      - /app/dist
      - /app/.pytest_cache
      - /app/.idea
      - /app/.cache
      - /app/htmlcov
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_PROFILE
      - AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN
